CREATE DATABASE IF NOT EXISTS  AdLlister;

USE AdLlister;

CREATE TABLE IF NOT EXISTS users(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(150) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ads(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(100) NOT NULL ,
  description VARCHAR(500) NOT NULL ,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS user_ad(
  user_id INT UNSIGNED NOT NULL,
  ads_id INT UNSIGNED NOT NULL,
  PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS categories(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  category VARCHAR(100) NOT NULL ,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ad_category(
  ads_id INT UNSIGNED NOT NULL,
  categories_id INT UNSIGNED NOT NULL
)

